### ISSUE TITLE
Develop Project Detail page

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#33]
## User Story

- [x] As a user, I want to be able to see the status of a project (_**TO BE FILLED LATER**_).

- [x] As a user, I want to quickly view the stats of the project (total swipes, contributors, and completed).

- [x] As a user, I want to be able view 
- the project description
- highlighted area and project point on the map
- a chart that shows the progress of the project

- [x] As a user, I want to be able to view the downloadable data in a card view so that I can find the right dataset and download it.

- [x] As a user, I want to be able to click on the download icon so that I can download the dataset.

**Comment by Shhhhhubh** [comment]
Updated User Stories : 
 - As a user, I want to be able to see the title, project status, project type, location, organization name, date, and contributors so that I can quickly see the meta details of the project.

- As a user, I want to quickly view the stats of the project (km2 and contributors).

- As a user, I want to be able view 
   - project overview next to the stats
    - map with highlighted area next to the progress chart

 - As a user, I want to be able to view the downloadable data in a card view so that I can find the right dataset and download it.

 - As a user, I want to be able to click on the download button so that I can download the dataset.
