### ISSUE TITLE
Data > Map - Integrate a Map component

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#38]
## User Story

- [x] As a user, I want to be able to see all the active, finished, and inactive color coded projects so that I can quickly figure out the project status.

- [x] As a user, I want to be able to hover on a point on the map so that I can see more information about the project quickly.

- [x] As a user, I want to click on a point on the map so that I am redirected to the Project Detail page.

**Comment by Shhhhhubh** [comment]
## Updated User stories 

 - As a user, I want to be able to see all the active, and finished color coded projects so that I can quickly figure out the project status.

 - As a user, I want to be able to click on a point on the map so that I can see more information about the project quickly via a tooltip.

 - As a user, I want to be able to click on the project name of the tooltip so that I am redirected to the Project Details  page.
