### ISSUE TITLE
Data > Filter - Add filters affecting the below components

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#40]
## User Story

- [x] As a user, I want to filter the projects based on project name, project completion date, and mission type so that I can find the project more conveniently in the #38 and #39

**Comment by Shhhhhubh** [comment]
## Updated User Stories 
 - As a user, I want to filter the projects based on project name, project status, project completion date (optional), organization (optional), project date (optional), and scale so that I can find the project more conveniently in the [map] and [card view]

 - As a user, I want to be able to see the updated project completed and area mapped numbers as per the applied filter.
