### ISSUE TITLE
Setup a transifex project within mapswipe organization for the community website

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#56]

**Comment by laurentS** [comment]
Can I just suggest considering whether a new project is needed? It is quite a lot of work getting users onto each of them, so if there's a sizeable groupe already (I'm not sure), maybe it's worth repurposing the existing project for this? If not, ignore me :)

**Comment by tnagorra** [comment]
We are revamping the website and it has a lot of changes so thought that it would be easier to start with a new project. But, we can also use the existing mapswipe website as they are both file based transifex project. We might need to change the github integration settings and it should work.

We have created a private transifex project to check the github integration and it is working well.
Just creating an issue to make sure we do not forget about the integration with the transifex project in Mapswipe.

**Comment by kopitek8** [comment]
@jhenshall @danbjoseph Reiterating the issue

**Comment by jhenshall** [comment]
Hi @kopitek8 - can you confirm whether we are creating a new project or repurposing the existing? Noting @laurentS comment - I will create a message for all our contributors noting any changes.

**Comment by AdityaKhatri** [comment]
@jhenshall Based on the call last week, let's create a new project under Mapswipe organization.
cc: @danbjoseph @kopitek8

**Comment by danbjoseph** [comment]
the language teams are set at the MapSwipe org level on Transifex, so all the people assigned to a language currently should have the same access to the new website project as they do to the app and old website.
 
@jhenshall i think we should hold off on a communication until all website content is finalized (including copy edits) so that people don't get started translating only to have their work wiped out by minor changes. 

@AdityaKhatri what do you need from us to move forward with this?

**Comment by AdityaKhatri** [comment]
Hey @danbjoseph , we've got the access for now, so nothing required at the moment.
