### ISSUE TITLE
General - Can we rethink the colors used in the MapSwipe Website at the moment?

### ISSUE THREAD

**Issue by kopitek8** [mapswipe/website#92]
## Why?

Because we are moving toward the approach of making the website much more interactive and playful

**Comment by kopitek8** [comment]
![Image](https://github.com/mapswipe/community-website/assets/25280806/6a525258-b889-443d-936f-be66a7e2d466)

**Comment by Katbaloo** [comment]
Just want to reinterate what we shared in our call on this question:
We are open to seeing suggestion option(s), however, it is unlikely that we will be able to significantly deviate from the current colors.  At some future date we may revisit an overall brand refresh which would include a rethink of the colors etc. which would also then be reflected in an app redesign so that the two properties are branding consistent.

**Comment by jhenshall** [comment]
With the illustrations, icons and design in full flow, it would be good to have a discussion to nail down the palette used and style guide. 

Noting the [style guides in figma](https://www.figma.com/file/07GYjgb68GJuFqZjR3SwbG/Mapswipe-Website?type=design&node-id=0-1&t=TX7FRFEiWmLTc5SI-0) and the colours used on the [community statsboard](https://community.mapswipe.org/), can we have a call early next week to finalise things?

**Comment by kopitek8** [comment]
@Smritikafle123 to update the styleguide with the latest
